spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieclub
    username: root
    password: admin
  liquibase:
    contexts: prod
  h2:
    console:
      enabled: false
  web:
    resources:
      static-locations: classpath:/static/,file:/Users/norbx/uploads/
app:
  storage:
    location: /Users/norbx/uploads/